providers = ["python"]

[variables]
NIXPACKS_PYTHON_VERSION = "3.11"
PYTHONPATH = "/app"

[phases.install]
cmds = ["pip install -r backend/requirements.txt"]

[start]
cmd = "cd backend && python app.py"
