[build]
builder = "nixpacks"

[deploy]
startCommand = "python start.py"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
healthcheckPath = "/health"
healthcheckTimeout = 30

[variables]
PORT = "5000"
FLASK_ENV = "production"
SECRET_KEY = "your-secret-key-change-me"
ALLOWED_ORIGINS = "https://*.vercel.app,http://localhost:3000"
