[build]
builder = "nixpacks"

[deploy]
startCommand = "python start.py"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
healthcheckPath = "/health"
healthcheckTimeout = 30

# Note: Set environment variables in Railway dashboard instead of here
# DATABASE_URL, SECRET_KEY, ALLOWED_ORIGINS, etc.
